name: Build vue & SCP transcfer files to EC2

on:
  push:

jobs:
  scpupload:
    runs-on: ubuntu-latest

    steps:
      #このymlが使われるリポジトリをチェックアウトしてビルドします。
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build vue
        run: |
          cd front_v_tail
          npm install
          npm run build
          pwd
          ls
      # # ファイルを指定したディレクトリに移動
      # - name: Copy files to target directory
      #   run: |
      #     mkdir html
      #     cp -R front_v_tail/dist/* html

      # EC2インスタンス上のターゲットディレクトリを事前に削除
      - name: Remove target directory on Lightsail & Set permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          #distディレクトリの保存先は/home/ec2-user/mdblog2_backend/mdblog2_frontend_vt/front_v_tail/distです。これを削除します。
          script: |
            sudo rm -rf /home/ec2-user/mdblog2_backend/mdblog2_frontend_vt/front_v_tail/dist
            

      #チェックアウトしたリポジトリ内のfront_v_tail/index.htmlをEC2の/tmpにアップロードします
      - name: Upload files by SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          source: "/home/runner/work/mdblog2_frontend_vt/mdblog2_frontend_vt/front_v_tail/dist/*"
          target: "/home/ec2-user/mdblog2_backend/mdblog2_frontend_vt/front_v_tail/dist"
      # - name: Reset permissions on EC2
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     port: ${{ secrets.SSH_PORT }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.SSH_PASS }}
      #     script: sudo chmod -R 755 /usr/share/nginx