name: Build vue & SCP transfer files to Lightsail & Restart docker-compose -d

on:
  push:

jobs:
  scpupload:
    runs-on: ubuntu-latest

    steps:
      #このymlが使われるリポジトリをチェックアウトしてビルドします。
      - name: Checkout repository 
        uses: actions/checkout@v3
      - name: Build vue
        run: |
          cd front_v_tail
          npm install
          npm run build
      # EC2インスタンス上のターゲットディレクトリを事前に削除
      - name: Remove target directory on Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          #lightsailのビルドデータの保存先は、/home/ec2-user/mdblog2_backend/mdblog2_frontend_vt/front_v_tail/distです。このディレクトリそのものを中身もふくめ削除します。
          script: |
            sudo rm -rf /home/ec2-user/mdblog2_backend/mdblog2_frontend_vt/front_v_tail/dist
      #Githubインスタンスのビルド済みデータはfront_v_tail/distにあります。
      #appleboy/scp-action@masterはsourceに記載のGithubインスタンスのディレクトリを全部再帰的にコピーするので、
      #source:front_v_tail/distとしたなら、Lightsailのmdblog2_frontend_vtにコピーする必要がある。(この場所ならfront_v_tail/distが存在していいから)
      # ※distディレクトリだけをコピーしたいなら、Githubインスタンスの上位に、コピーしたいデータを確保してから「source: 1つのディレクトリだけ」とする必要がある
      - name: Upload files by SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          source: "front_v_tail/dist"
          target: "/home/ec2-user/mdblog2_backend/mdblog2_frontend_vt/"
      # lightsailインスタンス上で、docker composeを一度ダウン→デーモンモードで再起動します。
      - name: Restart Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          script: |
            cd /home/ec2-user/mdblog2_backend
            docker compose -f dc_base.yml -f dc_prod.yml down
            docker compose -f dc_base.yml -f dc_prod.yml up -d
